# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [2]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [3]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [4]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [5]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x13165e6e690
byteorder:  little
byteswap:  False
type: int32


In [6]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [9]:
# створити масив 3х3 випадкових значень 
arr = np.random.randint(0, 100, (3, 3))
print(arr)

[[18 35 65]
 [89 50  7]
 [20 18 20]]


In [10]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [11]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[18 35 65]
 [89 50  7]
 [20 18 20]]
...
int32
(3, 3)
3
2
9
4
36


In [12]:
arr.__sizeof__()

164

### ЗАВДАННЯ 1

In [13]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)

print(arr1_1, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr1_1.dtype)
# інспектування розмірності массиву `shape`
print(arr1_1.shape)
# інспектування довжини масиву `len`
print(len(arr1_1))
# інспектування кількості вимірів масиву `ndim`
print(arr1_1.ndim)
# інспектування кількості елементів в масиві `size`
print(arr1_1.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr1_1.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr1_1.nbytes)

[[0.21814156 0.3254913  0.81041798 0.07081104]
 [0.1446821  0.71801068 0.9543798  0.50837323]
 [0.20016185 0.89346366 0.32665591 0.6345242 ]]
...
float64
(3, 4)
3
2
12
8
96


In [14]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(["a", "b", "c", "d", "e"])
print(arr1_2)

['a' 'b' 'c' 'd' 'e']


In [15]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4), dtype="float")
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [16]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [18]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [19]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [20]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3, 1, 3), False)
...
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [21]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3, 3))
...
print(arr2_2)

[[False False False]
 [False False False]
 [False False False]]


In [22]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape((2, 3))
...
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [23]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [24]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[36 35 46 10]
 [36 28 31 43]
 [47 40 18 18]
 [29 40 23 40]]


In [25]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

43


In [26]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[29 40 23 40]


In [27]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[36 35 46 10]
 [36 28 31 43]]


In [28]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[35 46]
 [28 31]
 [40 18]
 [40 23]]


In [29]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[36 35 46 10]
 [47 40 18 18]]


In [30]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[36 35 46 36 28 31 43 47 40 29 40 23 40]


### ЗАВДАННЯ 3

In [31]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[80 38 49 95 13]
 [72 11 65 14 99]
 [82 77 34 61 49]
 [62 41 62 44 43]]


In [32]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

65


In [33]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[72 11 65 14 99]


In [34]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2]
print(vect3_4)

[49 65 34 62]


In [35]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[11 65]
 [77 34]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [36]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [38]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.06741542 0.10449378 0.08974126 0.52768829 0.2083231 ]
 [0.89164215 0.06182964 0.76661102 0.67183433 0.71793772]
 [0.67687664 0.96809224 0.6747831  0.79405018 0.24053244]
 [0.47135925 0.34966417 0.05475117 0.87019923 0.5827735 ]
 [0.12485816 0.70770862 0.24941963 0.87848303 0.45809771]]
...
[0.06741542 0.06182964 0.6747831  0.87019923 0.45809771]


In [39]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.06741542 0.89164215 0.67687664 0.47135925 0.12485816]
 [0.10449378 0.06182964 0.96809224 0.34966417 0.70770862]
 [0.08974126 0.76661102 0.6747831  0.05475117 0.24941963]
 [0.52768829 0.67183433 0.79405018 0.87019923 0.87848303]
 [0.2083231  0.71793772 0.24053244 0.5827735  0.45809771]]


In [40]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.053814339264986424


In [41]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.55098379 -0.25031506  1.01417704  1.79216048 -2.16956517]
 [-2.51994879 -0.41633335  0.34299381  0.34197745  1.1833031 ]
 [ 1.07476041  1.03973418  0.01635186 -2.38398599  0.90598333]
 [ 3.77265838 -0.49300463  0.50040557 -0.00933508 -1.19386936]
 [-3.77670181  1.09073381 -1.77482713  0.2991226   2.74238017]]


### ЗАВАДАННЯ 4

In [42]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.linspace(100, 200, 36).reshape((6, 6))
print(mat4_1)

[[100.         102.85714286 105.71428571 108.57142857 111.42857143
  114.28571429]
 [117.14285714 120.         122.85714286 125.71428571 128.57142857
  131.42857143]
 [134.28571429 137.14285714 140.         142.85714286 145.71428571
  148.57142857]
 [151.42857143 154.28571429 157.14285714 160.         162.85714286
  165.71428571]
 [168.57142857 171.42857143 174.28571429 177.14285714 180.
  182.85714286]
 [185.71428571 188.57142857 191.42857143 194.28571429 197.14285714
  200.        ]]


In [43]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [44]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100.         117.14285714 134.28571429 151.42857143 168.57142857
  185.71428571]
 [102.85714286 120.         137.14285714 154.28571429 171.42857143
  188.57142857]
 [105.71428571 122.85714286 140.         157.14285714 174.28571429
  191.42857143]
 [108.57142857 125.71428571 142.85714286 160.         177.14285714
  194.28571429]
 [111.42857143 128.57142857 145.71428571 162.85714286 180.
  197.14285714]
 [114.28571429 131.42857143 148.57142857 165.71428571 182.85714286
  200.        ]]


In [45]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)

## 5. Операції над масивами

### ПРИКЛАДИ

In [46]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [47]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [48]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [49]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [50]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [51]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [52]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [53]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [71]:
# поелементний поділ
K = N / M
print(K)

[1. 1. 1. 1. 1.]


In [55]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [56]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [57]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [58]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [59]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [60]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[5 7 4 2 4]
[5 7 4 2 4]
1312082781616 1312082781616
[5 7 4 2 4]
1312082781616 1312082783632


In [61]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [96]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(0, 10, (4,3))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[3 0 1]
 [0 9 0]
 [7 1 8]
 [6 6 8]]
[ 4  9 16 20]


In [95]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

1


In [94]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[105 108 103]
 [103 102 105]
 [107 101 109]
 [109 101 106]]


In [108]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.multiply(mat5_1, np.diag(mat5_3))
print(mat5_4)


[[315   0 109]
 [  0 918   0]
 [735 102 872]
 [630 612 872]]


In [110]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = mat5_3 + mat5_4
print("Ранг матрицы: ", np.linalg.matrix_rank(mat5_5))

Ранг матрицы:  3
